---
title: "Shiny Apps"
author: "Yujin Zhang"
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

## This is for the topic of "shiny apps".

What is shiny? -Framework for building interactive plots and web applications in R.

Flexdashboard + Shiny

```{r, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(viridis)
library(plotly)
library(p8105.datasets)
```



```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, stars, price, room_type, lat, long
  ) %>% 
  drop_na(stars)
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_choice =
  nyc_airbnb %>% 
  distinct(borough) %>% 
  pull()

selectInput(
  "borough_choice",
  label = h3("Select Borough"),
  choices = borough_choice,
  selected = "Manhattan"
)

min_price =
  nyc_airbnb %>% 
  distinct(price) %>% 
  min()

max_price =
  nyc_airbnb %>% 
  distinct(price) %>% 
  max()

sliderInput(
  "price_choice",
  label = h3("Select Price"),
  min = min_price, max = max_price, 
  value = c(100, 400)
  )
  
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  nyc_airbnb %>%
    filter(
      borough == input[["borough_choice"]],
      price > input[["price_choice"]][1], price < input[["price_choice"]][2]
    ) %>% 
    plotly(x = ~lat, y = ~long, 
           type = "scatter", 
           mode = "markers", 
           color = ~price, alpha = .5)
  
  input[["borough_choice"]]
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({
  input[["price_choice"]]
})
```

### Chart C

```{r}

```
