---
title: "Statistical Learning"
date: "12/2/2021"
output: github_document
---

## Topic is about "learning from data"

```{r}
library(tidyverse)
library(glmnet)

set.seed(11)

```



## Lasso
Predicting birth weight

```{r}
bwt_df = 
  read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")) %>% 
  sample_n(200)

```

Do the lasso

```{r}
y = bwt_df %>% pull(bwt)
x = model.matrix(bwt ~., bwt_df)[, -1]

# fit a lasso model
lambda_grid = 10 ^ (seq(3, -2, by = -0.1))


lasso_fit = glmnet(x, y, lambda = lambda_grid)

lasso_cv = cv.glmnet(x, y, lambda = lambda_grid)
lasso_opt = lasso_cv$lambda.min
```


```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>% 
  filter(term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda), y = estimate, group = term, color = term)) +
  geom_path() +
  theme(legend.position = "none")
```

## Cluster pokemons

```{r}
poke_df = 
  read_csv("./data/pokemon.csv") %>% 
  janitor::clean_names() %>% 
  select(hp, speed)

# take a look at data distribution
poke_df %>% 
  ggplot(aes(x = hp, y = speed)) + 
  geom_point()

```

Use kmeans to identify clusters.

```{r}
kmeans_fit =
  kmeans(x = poke_df, centers = 3)
poke_df =
  broom::augment(kmeans_fit, poke_df)    # function in the first place

poke_df %>% 
  ggplot(aes(x = hp, y = speed, color = .cluster)) +
  geom_point()


```

